services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./out/pgdata:/var/lib/postgresql:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
  migrate:
    image: migrate/migrate:v4.19.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations:z
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
  app:
    build: .
    restart: always
    environment:
      - PGX_CONN_DOCKER=${PGX_CONN_DOCKER}
    ports:
      - "9091:9091"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./out:out:z
